### PR TITLE
Implementation of Abundant Number in cpp. 

### PR DESCRIPTION
**Pull request by AniketDGiri**
# Description

Implementation of the Issue Abundant Number or not in cpp

Reference Issue number #348

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
NOTE: **Check boxes using [x]**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, with problem description and my name.
- [ ] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [x] I have starred this repository.
- [x] I have added a working sample/screenshot of the script.
- [x] I have checked for trailing spaces in file names and none have them.

### CODE REVIEW

**Comment by pratik-choudhari** [comment]
@AniketDGiri Mention issue and complete checklist

**Comment by AniketDGiri** [comment]
Hi Pratik, I have completed the checklist. Could you please tell me where should i mention the issue?

**Comment by AniketDGiri** [comment]
Hi Pratik, I Have also edit the description message with the issue no. Please let me know in case of any concerns.

**Comment by AniketDGiri** [comment]
I have made the required changes. Please let me know in case of any concerns.

**Comment by pratik-choudhari** [comment]
@AniketDGiri It's complete now!

**Pull request merged**
