### PR TITLE
Added Countdown Timer program

### PR DESCRIPTION
**Pull request by uddeshyatyagi**
# Description
This is a simple python program which can be used for countdown.
In this user is required to input any number in seconds and then it will automatically count to zero(0) seconds

### CODE REVIEW

**Comment by uddeshyatyagi** [comment]
Hey @pratik-choudhari, please review my PR and merge if found useful

**Comment by pratik-choudhari** [comment]
@uddeshyatyagi If you want to make this contribution, please create an issue first.

**Comment by uddeshyatyagi** [comment]
Hey @pratik-choudhari  i have created an issue and have linked my PR to it, so please review

**Comment by pratik-choudhari** [comment]
@uddeshyatyagi You have deleted what was in the PR description. It must be completed for PR merge.

**Comment by uddeshyatyagi** [comment]
@pratik-choudhari i am not able to complete the description with checkboxes,what should i do next?Should i create new pull request for the same? Please help

**Comment by pratik-choudhari** [comment]
@uddeshyatyagi Yes. Create new one.

**Pull request closed without merging**
