### PR TITLE
Inbuilt Sort using STL which is faster than all Sorting Techniques

### PR DESCRIPTION
**Pull request by Ankit123848**
**Description**
-> Implemented Inbuilt Sort using standard template library in C++ in sortingMethods
-> bool compare function is used which is used as Comparator Function in STL
   if(a>b)-->it will sort in decreasing order
   if(a<b)-->it will sort in increasing order
-> It is faster than all sorting techniques like bubble sort , insertion sort
-> Time Complexity become Optimised
-> Comparator function can be used to compare not only numbers but also strings and character array
 #Reference Issue Number #closed #434

**Checklist:**
   I have read the project guidelines.
   I have checked all the existing projects, before submitting a new project issue.
   This issue will be meaningful for the project.
   I will contribute more in future

### CODE REVIEW

**Comment by pratik-choudhari** [comment]
@Ankit123848 mention issue

**Comment by Ankit123848** [comment]
This pull request has not associated with any reference issue number...This
is a new project that I want to add under sorting folders

**Comment by pratik-choudhari** [comment]
@Ankit123848 So you have not read the code of conduct. It states that you can't contribute just by putting up a PR, that will be labelled invalid. Rather you must create an issue first and get yourself assigned.

**Comment by Ankit123848** [comment]
I have read all the instructions and to be honest I am not able to find
issue number earlier
I have made the changes...Please accept the request

**Comment by Ankit123848** [comment]
I am contributing to open source 1st time .
Honestly I have searched for issue number but not find it earlier. It would
be really great if you remove invalid label otherwise I will not be
eligible for hacktoberfest.

**Comment by pratik-choudhari** [comment]
@Ankit123848 Invalid does not make you ineligible for hacktoberfest. To correct this, go to issues section and put the problem that you have solved in this PR. There I will assigned you and tell you the next steps.

**Pull request closed without merging**
