### PR TITLE
Doubly linked list in c/c++

### PR DESCRIPTION
**Pull request by rishika-singh49**
# Description

A comprehensive description about the Pull Request

Reference Issue number #(issue_no)

`issue_no` must refer to the issue related to this PR, visit [here](https://github.com/pratik-choudhari/AlgoCode/issues)

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
NOTE: **Check boxes using [x]**

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation Update

# Checklist:

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, with problem description and my name.
- [x] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [x] I have starred this repository.
- [ ] I have added a working sample/screenshot of the script.
- [ ] I have checked for trailing spaces in file names and none have them.

### CODE REVIEW

**Comment by rishika-singh49** [comment]
#Thankstober

**Comment by pratik-choudhari** [comment]
@rishika-singh49 new to git github?

**Comment by rishika-singh49** [comment]
@pratik-choudhari  yes sir...

**Comment by pratik-choudhari** [comment]
@rishika-singh49 What were not supposed to do:
* Place code and readme in a single readme file.

What to do now:
* create a separate file for the code.
* a readme explaining the problem and your name with github profile link.

**Comment by rishika-singh49** [comment]
i have done some changes please check it out

**Comment by pratik-choudhari** [comment]
@rishika-singh49 No No! You have changed the main README inside C/C++ folder, you are not supposed to do that.

**Comment by rishika-singh49** [comment]
But I have already created a file named doubly linked list in which I have
placed the code and it's output.

**Comment by pratik-choudhari** [comment]
@rishika-singh49 So if you have created a separate code file then you have committed the changes, push it to the fork and  make another PR. Ask doubts if any. Closing this PR.

**Comment by rishika-singh49** [comment]
Can I still update the code

**Comment by pratik-choudhari** [comment]
@rishika-singh49 Yes you can just create another PR when done.

**Comment by rishika-singh49** [comment]
I have tried to do but it gave an error when I requested to push

**Comment by pratik-choudhari** [comment]
Oh can you put an SS here?

**Pull request closed without merging**
