### PR TITLE
Sort it out v2.0 in Java

### LINKED ISSUE #94: Let's sort it out v2.0
# Feature ✅

## Description
The task is to implement:
* Merge sort
* Shell sort
* Radix sort

## Example
First input will be name of algorithm followed by list of integers in next line.
Input: Shell
1 8 3 9 33 02 0 93 64 22 1 35

Output: sorted list of input

__You are encourage not to copy code from online sources just for the name of open source contribution__

__Mention language in comments__

### PR DESCRIPTION
**Pull request by dhrubajyoti89**
# Sorting Algorithms in Java

- Selection sort
- Bubble sort
- Insertion sort

Fixed #94 

# Checklist:

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, with problem description and my name.
- [ ] I have included a requirements.txt file (if external libraries are required.)
- [ ] My changes do not produce any warnings.
- [ ] I have starred this repository.
- [ ] I have added a working sample/screenshot of the script.
- [ ] I have checked for trailing spaces in file names and none have them.
- [x] I have added \(your-name)[your-github-profile-link] in CONTRIBUTORS.md

### CODE REVIEW

**Comment by dhrubajyoti89** [comment]
invalid? @pratik-choudhari

**Comment by pratik-choudhari** [comment]
Yes @dhrubajyoti89 read this issue [here](https://github.com/pratik-choudhari/AlgoCode/issues/114)

**Comment by dhrubajyoti89** [comment]
but i was assigned for this issue ? #94 @pratik-choudhari

**Comment by pratik-choudhari** [comment]
No @dhrubajyoti89 you can verify!

**Pull request closed without merging**
