### PR TITLE
Number system conversion added in C#

### PR DESCRIPTION
**Pull request by itayz1230**
# Description

My first PR! Added number system conversion in `C#`!

**Please give me feedback about the process of the PR, Thank You!**

Reference Issue number #264 

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
NOTE: **Check boxes using [x]**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have created a helpful and easy to understand `README.md`, with problem description and my name.
- [ ] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [x] I have starred this repository.
- [ ] I have added a working sample/screenshot of the script.
- [x] I have checked for trailing spaces in file names and none have them.

### CODE REVIEW

**Comment by pratik-choudhari** [comment]
@itayz1230 22 files?

**Comment by itayz1230** [comment]
@pratik-choudhari  yes. It is all of the c# extra files so that it can work... Should I delete them and push only the program one? 
Sorry I'm new to all this 😃🙂

**Comment by pratik-choudhari** [comment]
Will deleting rest of the files hamper the code execution? or are these config files which every c# user has?

**Comment by itayz1230** [comment]
@pratik-choudhari These are only files that allow the program to run, only one file contains the code. Deleting the other files won't affect the code. If you can run C# on your machine, you should be able to just use the code file

**Comment by pratik-choudhari** [comment]
Alright then delete rest of them.

**Comment by itayz1230** [comment]
@pratik-choudhari cool, So I make another PR?

**Comment by pratik-choudhari** [comment]
Yes

**Pull request closed without merging**
