### PR TITLE
38: Scrape CodeChef's Problems

### PR DESCRIPTION
**Pull request by andre-silva-14**
# Description

A Program that scrapes the problem's information of a CodeChef's problem with the given problem code by the user, and saves all information in a text-based file.

Reference Issue number #38 

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
NOTE: **Check boxes using [x]**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, with problem description and my name.
- [x] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [x] I have starred this repository.
- [ ] I have added a working sample/screenshot of the script.
- [x] I have checked for trailing spaces in file names and none have them.

### CODE REVIEW

**Comment by andre-silva-14** [comment]
@pratik-choudhari I was not sure if this should go into `Projects` or `Python`. Tell me if you need me to change the directory. Thanks.

**Comment by pratik-choudhari** [comment]
@andre-silva-14 It must go inside Projects.

**Comment by andre-silva-14** [comment]
@pratik-choudhari Done. Thanks.

**Comment by pratik-choudhari** [comment]
@andre-silva-14 Awesome!

**Pull request merged**
