### PR TITLE
Added code to check HarshadNumber or not in Java

### PR DESCRIPTION
**Pull request by kusumapriyankaajjarapu**
# Description

Added code to check HarshadNumber or not. A Harshad Number is a number divisible by the sum of it's digits. Eg: 111 is divisible by 3(1+1+1).

Reference Issue number #347 

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
NOTE: **Check boxes using [x]**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, with problem description and my name.
- [ ] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [x] I have starred this repository.
- [ ] I have added a working sample/screenshot of the script.
- [x] I have checked for trailing spaces in file names and none have them.

### CODE REVIEW

**Comment by kusumapriyankaajjarapu** [comment]
Added code to check HarshadNumber or not in Java #347

**Comment by pratik-choudhari** [comment]
@kusumapriyankaajjarapu Refer all issues in PR desc.

**Comment by kusumapriyankaajjarapu** [comment]
@pratik-choudhari updated

**Comment by pratik-choudhari** [comment]
@kusumapriyankaajjarapu Why did you alter code of other 2 contributors?

**Comment by kusumapriyankaajjarapu** [comment]
Actually it's my first pull request. If I had done any wrongs please excuse me. But I haven't modified the code of other contributors

**Comment by pratik-choudhari** [comment]
@kusumapriyankaajjarapu You have already contributed and your PR is merged check [here](https://github.com/pratik-choudhari/AlgoCode/tree/master/Java/HarshadNumber%20or%20not). Closing this.

**Pull request closed without merging**
