### PR TITLE
Fenwick trees in C++

### PR DESCRIPTION
**Pull request by cs-mshah**
# Description

Fenwick trees in C++ implemented with README.

Reference Issue number #468 

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, with problem description and my name.
- [x] My changes do not produce any warnings.

### CODE REVIEW

**Comment by cs-mshah** [comment]
@pratik-choudhari I have made the PR according to the guidelines. Please check and accept the PR. I truly enjoyed contributing to this repository and taking part in the Hacktoberfest. Got to learn a lot!!

**Comment by pratik-choudhari** [comment]
@cs-mshah Thanks a lot! It was a pleasure having you :)

**Comment by cs-mshah** [comment]
@pratik-choudhari my PR has been marked invalid and I don't know why. A previous PR on this same repo got accepted but this one is invalid.

**Comment by pratik-choudhari** [comment]
@cs-mshah Oh, that's weird. The repository is still labeled hacktoberfest.

**Comment by pratik-choudhari** [comment]
i have another extra label let me know

**Comment by cs-mshah** [comment]
I don't think anything is possible now. They've labelled it ineligible. They haven't even put any contact so I can tell them.

**Comment by pratik-choudhari** [comment]
@cs-mshah Ohh, did you make extra PR?

**Pull request merged**
