### PR TITLE
Added python code for scrapping Dictionary.com

### PR DESCRIPTION
**Pull request by Blastoise**
Python Code for Scrapping Dictionary.com for all the words and with their meanings. I have also added requirements.txt so that the user does not face any issue. README.md is also added as mentioned in the rules.

### CODE REVIEW

**Comment by pratik-choudhari** [comment]
Hey @Blastoise This is great, could you add screenshot of json file and put it in the readme and make another PR, I appreciate your efforts

**Comment by Blastoise** [comment]
@pratik-choudhari Yes, I can add the screenshot of the JSON but the json will not contain all the words since in Dictionary.com there are approx 2,15,000 words and scrapping them all with their meaning will take a lot of time.

**Comment by pratik-choudhari** [comment]
Just a screen full of words will do

**Comment by Blastoise** [comment]
@pratik-choudhari There you go.
Screenshot from 2020-10-02 14-17-16

**Pull request merged**
