### PR TITLE
sqlite CRUD opertion added in python

### PR DESCRIPTION
**Pull request by Naziya-Parveen**
# Description

sqlite CRUD opertion added in python

Reference Issue number #197 

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
NOTE: **Check boxes using [x]**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:

- [ X] I have named my files and folder, according to this project's guidelines.
- [ X] My code follows the style guidelines of this project.
- [ X] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [ X] I have commented on my code, particularly in hard-to-understand areas.
- [ X] I have created a helpful and easy to understand `README.md`, with problem description and my name.
- [ X] I have included a requirements.txt file (if external libraries are required.)
- [ X] My changes do not produce any warnings.
- [ X] I have starred this repository.
- [ X] I have added a working sample/screenshot of the script.
- [ X] I have checked for trailing spaces in file names and none have them.
- [ X] I have added \(your-name)[your-github-profile-link] in CONTRIBUTORS.md

### CODE REVIEW

**Comment by pratik-choudhari** [comment]
@Naziya-Parveen All these should be in a single file and user can perform crud for terminal itself. The program must be menu driven.

**Comment by Naziya-Parveen** [comment]
Please check it now.

**Comment by pratik-choudhari** [comment]
@Naziya-Parveen `'clear' is not recognized as an internal or external command,
operable program or batch file.` Warning during exec.

**Comment by Naziya-Parveen** [comment]
Screenshot (32)
It's working perfectly fine. You can replace clear() with cls() if clear() is not supported.

**Comment by pratik-choudhari** [comment]
@Naziya-Parveen Could you add that as a comment?

**Comment by Naziya-Parveen** [comment]
@pratik-choudhari I have added. Please check the README.md file.

**Pull request merged**
