### PR TITLE
Postfix to Prefix conversion #369

### LINKED ISSUE #369: Postfix to Prefix Conversion
# Feature ✅

## Description

Conversion input infix equation to postfix expression

## Example

<b>Input:</b> XY+UV-/
<b>Output:</b> /+XY-UV

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

__Contributors are supposed to mention their coding language while asking for assignment__

### PR DESCRIPTION
**Pull request by uddeshyatyagi**
# Description

A comprehensive description about the Pull Request

Reference Issue number #issue_no

`issue_no` must refer to the issue related to this PR, visit [here](https://github.com/pratik-choudhari/AlgoCode/issues)

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
NOTE: **Check boxes using [x]**

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, with problem description and my name.
- [ ] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [x] I have starred this repository.
- [ ] I have added a working sample/screenshot of the script.
- [x] I have checked for trailing spaces in file names and none have them.

closes #369

### CODE REVIEW

**Comment by pratik-choudhari** [comment]
@uddeshyatyagi You are not assigned.

**Comment by uddeshyatyagi** [comment]
Hey @pratik-choudhari, then please assign the issue to me,reopen the pull request and merge it if possible!!

**Comment by pratik-choudhari** [comment]
@uddeshyatyagi Comment on the issue and reference it here.

**Comment by pratik-choudhari** [comment]
@uddeshyatyagi Still you have not referred to the issue number in PR description. I am going to merge this, next time follow the code of conduct.

**Pull request merged**
