### PR TITLE
added armstrong number in python

### PR DESCRIPTION
**Pull request by ayu16**
# Description

A comprehensive description about the Pull Request

Fixes #(issue_no)

`issue_no` must refer to the issue related to this PR, visit [here](https://github.com/pratik-choudhari/AlgoCode/issues)

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
NOTE: **Check boxes using [x]**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:

- [ ] I have named my files and folder, according to this project's guidelines.
- [ ] My code follows the style guidelines of this project.
- [ ] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have created a helpful and easy to understand `README.md`, with problem description and my name.
- [ ] I have included a requirements.txt file (if external libraries are required.)
- [ ] My changes do not produce any warnings.
- [ ] I have starred this repository.
- [ ] I have added a working sample/screenshot of the script.
- [ ] I have checked for trailing spaces in file names and none have them.

### CODE REVIEW

**Comment by pratik-choudhari** [comment]
@ayu16 Please follow code of conduct. Arrange contribution as mentioned in the same.

**Comment by pratik-choudhari** [comment]
@ayu16 Still you haven't arranged files as required, do you have experience of git and github? If no I will guide you.

**Comment by ayu16** [comment]
> @ayu16 Still you haven't arranged files as required, do you have experience of git and github? If no I will guide you.

no, I actually don't have experience in git and GitHub, please guide me

**Comment by pratik-choudhari** [comment]
@ayu16 First things first you have merged the armstrong number PR with the sorting PR.
* A PR should follow it's title.
* For different problem there must be a separate PR.

Secondly, the name of files is not apt, for instance `shell sort in python` is illegal. It must be shell_sort.py as .py explains it is a python file.

Thirdly, You have placed the sorting files in main repo directory, they must be placed inside Python/Sortingalgorithms2.0 name and armstrong_number.py must be placed inside Python/ArmstrongNumber/

**Comment by ayu16** [comment]
okay, I'll do this all by tomorrow...

**Comment by ayu16** [comment]
did I make the changes right this time?

**Comment by pratik-choudhari** [comment]
@ayu16 Actually no. Not all files are renamed. And you must placed them in folder as mentioned in last message.

**Comment by ayu16** [comment]
okay working out on that

**Pull request closed without merging**
