### PR TITLE
Searching Algorithms in C++

### LINKED ISSUE #120: Searching Algorithms
# Feature ✅

## Description
Searching Algorithms:
- [ ] Binary Search
- [ ] Fibonacci Search
- [ ] Linear Search
- [ ] Ternary Search
- [ ] Median Search

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked all the existing projects, before submitting a new project issue.
- [x] This issue will be meaningful for the project.
- [x] I will contribute more in future

### PR DESCRIPTION
**Pull request by dhrubajyoti89**
# Searching Algorithms in C++

Implementations of:

- Binary Search
- Fibonacci Search
- Linear Search
- Ternary Search
- Median Search

resolved #120 

## Checklist:

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, with problem description and my name.
- [ ] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [ ] I have starred this repository.
- [ ] I have added a working sample/screenshot of the script.
- [ ] I have checked for trailing spaces in file names and none have them.

### CODE REVIEW

**Comment by dhrubajyoti89** [comment]
@pratik-choudhari kindly review

**Comment by pratik-choudhari** [comment]
@dhrubajyoti89 This will be your last contribution to this repo (Max 2). Thanks for stopping by✌

**Comment by dhrubajyoti89** [comment]
Kindly assign the hacktoberfest-accepted tag @pratik-choudhari

**Comment by dhrubajyoti89** [comment]
Kindly assign the hacktoberfest-accepted label @pratik-choudhari

**Comment by pratik-choudhari** [comment]
@dhrubajyoti89 that label is not required as this PR is merged. It is required when PR is not merged but maintainer wants it to be counted for hacktoberfest.

**Pull request merged**
