### PR TITLE
Inbuilt Sort which is faster than all Sorting Techniques

### PR DESCRIPTION
**Pull request by Ankit123848**
Implemented in C++ Language in sortingMethods folder
Implemented Inbuilt Sort using Comparator[bool compare function] which is used in Standard Template Library
Time Complexiry is Optimised using Inbuilt Sort
It is faster than all sorting techniques like Bubble Sort , Insertion Sort etc.
bool compare function  is used 
if(a>b) ->Sorts in ascending Order
if(a<b) ->Sorts in Descending Order
**bool compare function is generalised not only for numbers but also for strings and characters

### CODE REVIEW

**Comment by pratik-choudhari** [comment]
@Ankit123848 mention issue number

**Comment by Ankit123848** [comment]
Ok I will do it now...!!!
Please accept my pull request after that

**Comment by Ankit123848** [comment]
I have mentioned the Description and Checklist for my pull request but not
able to find Reference issue number for which you have mentioned github URL
Can you help me out with this?

**Comment by Ankit123848** [comment]
I have done all the changes...Plzz accept my pull request from new branch
"AkkiBranch" and also there is not any issue no related to my pull
request...It is a new file which I have contributed

**Pull request closed without merging**
