### PR TITLE
added code for number conversion

### PR DESCRIPTION
**Pull request by Bhavya-Tripathi**
# Description

Added a menu-driven code to convert a given number from one base system to another.

Reference Issue number #264 

`issue_no` must refer to the issue related to this PR, visit [here](https://github.com/pratik-choudhari/AlgoCode/issues)

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
NOTE: **Check boxes using [x]**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have created a helpful and easy to understand `README.md`, with problem description and my name.
- [ ] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [ ] I have starred this repository.
- [ ] I have added a working sample/screenshot of the script.
- [x] I have checked for trailing spaces in file names and none have them.

### CODE REVIEW

**Comment by Bhavya-Tripathi** [comment]
@pratik-choudhari I have added the code for number system conversion. Please review my pull request.

**Comment by pratik-choudhari** [comment]
@Bhavya-Tripathi Add a readme with your name and gh link. Also consider starring the repo☺

**Comment by Bhavya-Tripathi** [comment]
Sure thing 👍

**Comment by Bhavya-Tripathi** [comment]
I have made the required changes. Kindly review them @pratik-choudhari . Thanks!

**Pull request merged**
