### PR TITLE
Added EDA for StackOverflow 2019 Developer Dataset

### PR DESCRIPTION
**Pull request by sanskritip**
# Description

A comprehensive description about the Pull Request

Reference Issue number #162 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:

- [X] I have named my files and folder, according to this project's guidelines.
- [X] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, with problem description and my name.
- [x] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [x] I have starred this repository.
- [ ] I have added a working sample/screenshot of the script.
- [x] I have checked for trailing spaces in file names and none have them.

### CODE REVIEW

**Comment by pratik-choudhari** [comment]
@sanskritip You have made a draft PR

**Comment by sanskritip** [comment]
> 
> 
> @sanskritip You have made a draft PR

Hey I'll just add requirements.txt and un-draft it by tonight!

**Comment by pratik-choudhari** [comment]
@sanskritip Did you pip freeze and add it to requirements? because those are a lot of dependencies.

**Comment by sanskritip** [comment]
> 
> 
> @sanskritip Did you pip freeze and add it to requirements? because those are a lot of dependencies.

Yes, I did pip freeze in the virtual environment. A lot of the libraries used come with added dependencies which is kind of the reason for the large number. Is it an issue ?

**Comment by pratik-choudhari** [comment]
@sanskritip Yes, it is an issue. Those package versions might make a lot of other packages deprecated. Just include the packages which you have used and don't come preinstalled with python.

**Comment by sanskritip** [comment]
> 
> 
> @sanskritip Yes, it is an issue. Those package versions might make a lot of other packages deprecated. Just include the packages which you have used and don't come preinstalled with python.

Made the required changes! Thank you for pointing them out!

**Pull request merged**
