### PR TITLE
Searching Trees Algorithm Codes

### PR DESCRIPTION
**Pull request by Ritesh055**
# Description

Searching Trees Algorithm Codes

Fixes #(58)

`issue_no` must refer to the issue related to this PR, visit [here](https://github.com/pratik-choudhari/AlgoCode/issues)

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
NOTE: **Check boxes using [x]**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:

- [ x] I have named my files and folder, according to this project's guidelines.
- [x ] My code follows the style guidelines of this project.
- [ x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [ x] I have commented on my code, particularly in hard-to-understand areas.
- [ x] I have created a helpful and easy to understand `README.md`, with problem description and my name.
- [ x] I have included a requirements.txt file (if external libraries are required.)
- [ x] My changes do not produce any warnings.
- [x ] I have starred this repository.
- [x ] I have added a working sample/screenshot of the script.
AVL a
AVL b
B Tree
BST a
BST b
Interval Tree
Order Statistic Tree
RBT a
RBT b
RBT c
RBT d
RBT e
Skip List
Tries

 [x] I have checked for trailing spaces in file names and none have them.

### CODE REVIEW

**Comment by pratik-choudhari** [comment]
Add your name along with github profile link to readme as re issue PR

**Comment by Ritesh055** [comment]
In contributers.md, right?

**Comment by Ritesh055** [comment]
I have already added a Readme.md in the folder that has my name and github profile link.

**Comment by pratik-choudhari** [comment]
Contributors.md must not be altered whereas this [file](https://github.com/Ritesh055/AlgoCode/blob/master/C%20-%20C%2B%2B/searchingTrees/readme.md) must include your name and github link.

**Comment by Ritesh055** [comment]
I have added my name and profile link.

**Pull request merged**
