### PR TITLE
Added a program having fast algorithm of Fibonacci sequence 

### PR DESCRIPTION
**Pull request by atharvakarnik**
# Description

I've added a fast algorithm for calculation involving the Fibonacci sequence (Naive approach takes a ridiculous amount of time, even for smaller numbers like 50, 100, etc.). The complete description of the program can be found in the README.md file.
This pull request doesn't refer to any issue particularly, I've just my bit to this very helpful repository.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation Update

# Checklist:

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, with problem description and my name.
- [x] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [x] I have starred this repository.
- [x] I have added a working sample/screenshot of the script.
- [x] I have checked for trailing spaces in file names and none have them.

### CODE REVIEW

**Comment by pratik-choudhari** [comment]
@atharvakarnik This is an awesome contribution go ahead and create an issue about this problem, so others can contribute in different languages.

**Comment by atharvakarnik** [comment]
> @atharvakarnik This is an awesome contribution go ahead and create an issue about this problem, so others can contribute in different languages.

@pratik-choudhari Yes, sure!!

**Comment by atharvakarnik** [comment]
> @atharvakarnik This is an awesome contribution go ahead and create an issue about this problem, so others can contribute in different languages.

@pratik-choudhari I am unable to add labels to the issue I have created (#410), can you please do it? Also, if it is ok, can you close this pull request?

**Comment by pratik-choudhari** [comment]
@atharvakarnik Only maintainers can add labels and assign others. I will merge this PR itself, doesn't need to be closed. Cheers!

**Pull request merged**
