### PR TITLE
Identify floating point numbers - Python

### PR DESCRIPTION
**Pull request by TechnoPhasePRO**
Identify floating point numbers - Python

# Description
It checks for the user's input if it is a floating point or not.

Reference Issue number #104

`issue_no` must refer to the issue related to this PR, visit [here](https://github.com/pratik-choudhari/AlgoCode/issues)

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
NOTE: **Check boxes using [x]**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have created a helpful and easy to understand `README.md`, with problem description and my name.
- [ ] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [x] I have starred this repository.
- [ ] I have added a working sample/screenshot of the script.
- [x] I have checked for trailing spaces in file names and none have them.

### CODE REVIEW

**Comment by pratik-choudhari** [comment]
@TechnoPhasePRO Read the code of conduct and adhere to the directory structure.

**Comment by TechnoPhasePRO** [comment]
@pratik-choudhari  should i create a new directory for Python floating number or just add it to the existing c-c++ folder?

**Comment by pratik-choudhari** [comment]
new directory inside python folder.

**Comment by TechnoPhasePRO** [comment]
@pratik-choudhari Sir, I have created the directory please see to it.

**Comment by pratik-choudhari** [comment]
@TechnoPhasePRO Rename py file aptly and add a readme

**Pull request closed without merging**
