### PR TITLE
Closest 9's and 0's multiple

### PR DESCRIPTION
**Pull request by SHARC-99**
Closest 9's and 0's multiple

# Description

A comprehensive description about the Pull Request

Fixes #(issue_no)

`issue_no` must refer to the issue related to this PR, visit [here](https://github.com/pratik-choudhari/AlgoCode/issues)

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
NOTE: **Check boxes using [x]**

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, with problem description and my name.
- [ ] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [ ] I have starred this repository.
- [ ] I have added a working sample/screenshot of the script.
- [ ] I have checked for trailing spaces in file names and none have them.

### CODE REVIEW

**Comment by pratik-choudhari** [comment]
@SHARC-99 fill up the checklist in PR and abide.

**Comment by SHARC-99** [comment]
> @SHARC-99 fill-up the checklist in PR and abide.

 done!

**Review by SHARC-99 — COMMENTED** [review]
Checklist filled!

**Comment by pratik-choudhari** [comment]
@SHARC-99 The contribution should be inside `C - C++`

**Pull request closed without merging**
