### PR TITLE
Create PerfectNumber.cpp

### LINKED ISSUE #53: número perfecto🕶
# Feature ✅

## Description
Find all perfect number less than n

a perfect number is a positive integer that is equal to the sum of its positive divisors, excluding the number itself. For instance, 6 has divisors 1, 2 and 3 (excluding itself), and 1 + 2 + 3 = 6, so 6 is a perfect number. 

## Example
Input: 500

Output: 6 28 496

__Note: perfect numbers value escalate quickly, checkout the list [here](https://en.wikipedia.org/wiki/List_of_perfect_numbers)__

### PR DESCRIPTION
**Pull request by codermind-divya**
# Description

Added code for the perfect numbers less than n.

Fixes #53 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

### CODE REVIEW

**Comment by pratik-choudhari** [comment]
@codermind-divya Please first ask for assignment to this issue in preferred language.

**Comment by codermind-divya** [comment]
Sorry! I am new to open-source.
Can I work on this issue in c++.

**Comment by codermind-divya** [comment]
> @codermind-divya Please first ask for assignment to this issue in preferred language.
Sorry! I am new to open-source!
Can I work on this issue in C++?

**Comment by pratik-choudhari** [comment]
@codermind-divya Sure, just put a comment in the issue for assignment😄

**Pull request closed without merging**
