### PR TITLE
Python GEODATA

### PR DESCRIPTION
**Pull request by DishantIsrani**
# Description

A comprehensive description about the Pull Request

Reference Issue number #issue_no

`issue_no` must refer to the issue related to this PR, visit [here](https://github.com/pratik-choudhari/AlgoCode/issues)

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
NOTE: **Check boxes using [x]**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, with problem description and my name.
- [ ] I have included a requirements.txt file (if external libraries are required.)
- [ ] My changes do not produce any warnings.
- [x] I have starred this repository.
- [ ] I have added a working sample/screenshot of the script.
- [ ] I have checked for trailing spaces in file names and none have them.

### CODE REVIEW

**Comment by DishantIsrani** [comment]
This is a great repo @pratik-choudhari also thankyou for helping

**Comment by pratik-choudhari** [comment]
@DishantIsrani I am not sure if I understand the contribution, it's significance and application. Firstlt, this problem is not in the issues so first please create an issue and I will assign you there. Secondly, Format your readme using the markdown syntax, just a text file makes it ambiguous.

**Comment by pratik-choudhari** [comment]
@DishantIsrani Make the .txt file .md file

**Comment by DishantIsrani** [comment]
Done! Thanks @pratik-choudhari

**Comment by pratik-choudhari** [comment]
@DishantIsrani You have said that you included requirements file but can't see one.

**Comment by DishantIsrani** [comment]
Updates the files! @pratik-choudhari

**Pull request merged**
