### PR TITLE
Created Music Player Application in Python

### PR DESCRIPTION
**Pull request by sarthakw7**
# Description

A comprehensive description about the Pull Request

Reference Issue number #247

`issue_no` must refer to the issue related to this PR, visit [here](https://github.com/pratik-choudhari/AlgoCode/issues)

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
NOTE: **Check boxes using [x]**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:

- [ ] I have named my files and folder, according to this project's guidelines.
- [  ] My code follows the style guidelines of this project.
- [  ] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have created a helpful and easy to understand `README.md`, with problem description and my name.
- [ ] I have included a requirements.txt file (if external libraries are required.)
- [ ] My changes do not produce any warnings.
- [ ] I have starred this repository.
- [ ] I have added a working sample/screenshot of the script.
- [ ] I have checked for trailing spaces in file names and none have them.
- [  ] I have added \(your-name)[your-github-profile-link] in CONTRIBUTORS.md

### CODE REVIEW

**Comment by pratik-choudhari** [comment]
Add a requirements.txt

**Comment by pratik-choudhari** [comment]
Also @sarthakw7 there is no feature to pause music?

**Comment by pratik-choudhari** [comment]
@sarthakw7 Throws error when folder has no music files.
`Traceback (most recent call last):
  File "main.py", line 39, in <module>
    directorychooser()
  File "main.py", line 35, in directorychooser
    pygame.mixer.music.load(listofsongs[0])
IndexError: list index out of range`

**Comment by sarthakw7** [comment]
I will try to solve this problem

> 
> 
> @sarthakw7 Throws error when folder has no music files.
> `Traceback (most recent call last): File "main.py", line 39, in <module> directorychooser() File "main.py", line 35, in directorychooser pygame.mixer.music.load(listofsongs[0]) IndexError: list index out of range`

**Pull request closed without merging**
