### PR TITLE
Added C++ code for inplace rotation of a matrix by 90 degrees

### PR DESCRIPTION
**Pull request by SankethGB**
# Description

A comprehensive description about the Pull Request

Reference Issue number #191 )

`issue_no` must refer to the issue related to this PR, visit [here](https://github.com/pratik-choudhari/AlgoCode/issues)

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
NOTE: **Check boxes using [x]**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, with problem description and my name.
- [x] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [x] I have starred this repository.

- [x] I have checked for trailing spaces in file names and none have them.
- [x] I have added \(your-name)[your-github-profile-link] in CONTRIBUTORS.md

### CODE REVIEW

**Comment by SankethGB** [comment]
What is the mistake I have committed. I don't understand. The code couldn't be any cleaner. Do support good coders. I don't find your point in marking it invalid.

**Comment by pratik-choudhari** [comment]
@SankethGB Your code might be fine but you are not assigned to that issue, so you can't PR for it.

**Comment by SankethGB** [comment]
I don't understand the need for such assignment....at the end of the day my
intent was to contribute...if you don't want me to cool...closed chapter

**Comment by pratik-choudhari** [comment]
Contribution has to follow a decorum. If you don't want to follow that find some other repository.

**Comment by SankethGB** [comment]
I have already found repos. Dont mind :)
Its not open source if one assigns all tasks to girls and I will find open
source repos....

**Comment by pratik-choudhari** [comment]
@SankethGB Man you have some serious issues, you know that right?

**Pull request closed without merging**
