### PR TITLE
Implemented Count Single Digits in Java

### PR DESCRIPTION
**Pull request by dhairya-parikh**
# Description

**Question:** For a given number find out the count of digits appearing exactly once
**Example:**
Input: 99995844
Output: 2(only 5 and 8 appear once)

Reference Issue number #273

`issue_no` must refer to the issue related to this PR, visit [here](https://github.com/pratik-choudhari/AlgoCode/issues)

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
NOTE: **Check boxes using [x]**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, with problem description and my name.
- [ ] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [ ] I have starred this repository.
- [ ] I have added a working sample/screenshot of the script.
- [x] I have checked for trailing spaces in file names and none have them.

### CODE REVIEW

**Comment by dhairya-parikh** [comment]
May I know aa to when my name will be added to “Contributors.md” file ?

**Comment by pratik-choudhari** [comment]
@dhairya-parikh The contributor.md gets updated as soon as your name appears in contributors(below the repo description). As the process is automated it scrapes the contributors and then the MD is updated in github. It takes 24 hrs after your PR is merged to appear in contributors.

**Comment by dhairya-parikh** [comment]
Cool !!
Thanks for letting me know :)

**Comment by pratik-choudhari** [comment]
No problem😄

**Comment by pratik-choudhari** [comment]
@dhairya-parikh Have a look it has been added.

**Comment by dhairya-parikh** [comment]
Thanks 🤗

**Comment by dhairya-parikh** [comment]
I have implemented Sleep Sort Algorithm in Java. Would you like me to add
it to the repository ?

**Comment by pratik-choudhari** [comment]
@dhairya-parikh Sure, no problem. Create an issue for same.

**Pull request merged**
